# Generated by Django 3.2.8 on 2021-10-27 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='timeStamp',
        ),
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
